set top_module "mn_adder_wrapper"
set part_name "xc7a200tlffv1156-2L"
set proj_name "adder"
set user_sweep {
foreach param_N {32, 64, 96, 128, 256, 300}
for param_M {0 to $param_N} {2}
}

set tolerance 0.007
set cp 0.5

set wns 0
set wpws 0
set tns 0

set delay_summary [file join [pwd] delay_summary.txt]
set fid_delay_summary [open $delay_summary "w"]
puts $fid_delay_summary "\t\tclock_period\tWNS\tWPWS"
close $fid_delay_summary

proc fl_rep {cp count proj_id} {
	global clk_constraints
	global tolerance
	global wns
	global wpws
	global tns
	global summary
	
	reset_run synth_1; reset_run impl_1;

	set fid_clk_constraints [open $clk_constraints "w"]
	puts $fid_clk_constraints "create_clock -name clk -period $cp \[get_ports clk\]"
	close $fid_clk_constraints
	
	remove_files -fileset constrs_1 $clk_constraints 
	add_files -fileset constrs_1 $clk_constraints 
	
	launch_runs synth_1;
	wait_on_run synth_1;
	
	launch_runs impl_1;
	wait_on_run impl_1;
	open_run impl_1;
	
	set timing_summary [file join [pwd] design_sweep_runs ${proj_id} reports timing_summary_${count}.txt]
	report_timing_summary -file $timing_summary
	
	set fid_timing_summary [open $timing_summary "r"]
	set contents [read $fid_timing_summary]
	close $fid_timing_summary
	
	regexp -lineanchor {\n\s+([-0-9.]+)\s+([-0-9.]+)\s+\d+\s+\d+\s+([-0-9.]+)} $contents -> wns tns wpws
	
	set fid_summary [open $summary "a"]
	puts $fid_summary "Iteration ${count}\ncp:\t${cp}\nwns:\t${wns}\nwpws:\t${wpws}\n\n"
	close $fid_summary
}

proc get_delay {proj_id} {
	global clk_constraints
	global cp
	global tolerance
	global wns
	global wpws
	global tns
	global summary
	
	file mkdir [file join [pwd] design_sweep_runs ${proj_id} reports]
	
	set clk_constraints [file join [pwd] design_sweep_runs ${proj_id} clk_constraints.xdc]
	set summary [file join [pwd] design_sweep_runs ${proj_id} reports summary.txt]

	fl_rep $cp 1 $proj_id;
	
	set count 2
	while {$wns <0} {
		set cp [expr {$cp - $wns}]
		fl_rep $cp $count $proj_id
		set count [expr {$count + 1}]
	}
}

puts "\n\nThe operating clock pulse period is ${cp}. Corresponding WNS = ${wns} and WPWS = ${wpws}"

namespace eval gnspc {
	proc gen_modules {param_dict proj_id top_module} {

		file mkdir [file join [pwd] design_sweep_runs ${proj_id} design_modules]
		# setting variables (parameter values) from the dictionary
		foreach var [dict keys $param_dict] {
			dict get $param_dict $var
			set $var [dict get $param_dict $var]
			puts $var
		}

		# For case when rtl is being generated by tcl scripts
		if {[llength [glob -nocomplain [file join [pwd] rtl_src_dir *.tcl]]] > 0} {
			foreach rtl_gen_src [glob [file join [pwd] rtl_src_dir *.tcl]] {
				set rtl_destn [file join [pwd] design_sweep_runs ${proj_id} design_modules [file rootname [file tail $rtl_gen_src]].v]
				set fid_rtl_destn [open $rtl_destn "w"]
				source $rtl_gen_src
				puts $gen_dump
				puts $fid_rtl_destn $gen_dump
				close $fid_rtl_destn
			}
		}
		
		# For case when RTL is explicitly written in verilog
		if {[llength [glob -nocomplain [file join [pwd] rtl_src_dir *.v]]] > 0 } {
			foreach rtl_src [glob [file join [pwd] rtl_src_dir *.v]] {
				set rtl_content [read [open $rtl_src "r"]]
				# Overwrite the parameters if it is the top module 
				if {[file rootname [file tail $rtl_src]] == $top_module} {
					dict for {key value} $param_dict {
						regsub -all -- $key $rtl_content $value rtl_content
					}
				}
				set rtl_destn [file join [pwd] design_sweep_runs ${proj_id} design_modules [file tail $rtl_src]]
				set fid_rtl_destn [open $rtl_destn "w"]
				puts $fid_rtl_destn $rtl_content
				close $fid_rtl_destn
			}
		}
	}
}



proc flow {proj_id param_dict top_module} {
	#global top_module
	global part_name
	global delay_summary
	global cp
	global wns
	global wpws


	#create project
	create_project ${proj_id} [file join [pwd] design_sweep_runs ${proj_id}] -part $part_name
	
	#generate modules based on present parameter values
	gnspc::gen_modules ${param_dict} ${proj_id} ${top_module}
	
	#add files
	set design_modules [glob [file join [pwd] design_sweep_runs ${proj_id} design_modules *.v]]
	add_files -fileset sources_1 $design_modules
	update_compile_order -fileset sources_1
	
	
	#set top module
	set_property top $top_module [get_fileset sources_1]
	
	#call delay computation function
	get_delay $proj_id
	set fid_delay_summary [open $delay_summary "a"]

	puts $proj_id
	regexp {^[^_]+_(.*)} $proj_id -> trimmed 
	puts $fid_delay_summary "${trimmed}:  ${cp}\t${wns}\t${wpws}"
	close $fid_delay_summary
	set cp 0.5

        close_project
}

# Repeat flow for each parameter set

set lines [split $user_sweep "\n"]
set loop_body ""
set dict_def "set param_dict \[dict create "
set size 0
set id ""

foreach line $lines {
	if {[regexp {^foreach\s+(\w+)\s+\{(.*)\}} $line -> var list]} {
        	# Clean commas
        	regsub -all {,} $list "" clean_list
        	append loop_body "foreach $var \{$clean_list\} \{\n"
		append dict_def "$var \$${var} "
		set size [expr {$size + 1}]
    	}

	if {[regexp {^for\s+(\w+)\s+\{([^\s]+)\s+to\s+([^\}]+)\}\s+\{([^\}]+)\}} $line -> var start end step]} {
		append loop_body "for \{set $var $start\} {\$$var <= $end} \{incr $var $step\} \{\n"
		append dict_def "$var \$${var} "
		set size [expr {$size + 1}]
	}	
}
append loop_body [append dict_def "\]\n"]
append loop_body {dict for {key value} $param_dict {
	if {[regexp {param_(\w+)} $key -> suffix]} {
		append id "_${suffix}${value}"
	}
}
set proj_id "${proj_name}${id}"
set id ""
}
append loop_body "flow \$proj_id \$param_dict \$top_module\n"
append loop_body [string repeat } ${size}]


eval $loop_body

